### ISSUE TITLE
Mistakes in Chaper 1?

### ISSUE THREAD

**Issue by Bobby1984** [Apress/practical-system-programming-c#1]
Hi,
I have not found an errta on the apress site to post this, so i am doing that here. In Chapter 1 - Introduction to the Linux Environment it is repeatedly stated that the linux kernel is faster because the address space and user space are not shared. All 
other sources i found on the www state that a monolithic kernel is fast because the address space is shared. I am a bit confused now. 
Can you clarify.

Thanks and best regards

**Comment by srimanikantapalakollu** [comment]
@Bobby1984 Thanks for reaching your doubt. I am happy to help you to resolve it. Coming to your question Linux uses a monolithic kernel but when it comes to sharing of address spaces is going to happen virtually which is in the sense Address spaces in Linux are virtualized. Generally, improving the performance of the kernel in OS address spaces is virtualized, which ultimately increases performance. I hope this clears your doubt.
